Homework 03
elena-roshchina/ElenaRoshchina_LevelUP pull request #6
Opened 2020-12-02 22:03 UTC by elena-roshchina

2020-12-09 08:40 UTC, khda91 requested changes

2020-12-09 08:40 UTC, khda91 commented on src/main/java/ru/levelup/elena/roshchina/qa/homework_03/aircrafts/AirShip.java
> +import ru.levelup.elena.roshchina.qa.homework_03.aviaexceptions.IllegalAircraftSpecificationException;
Импорт есть, а исключения нету

2020-12-09 08:40 UTC, khda91 commented on src/main/java/ru/levelup/elena/roshchina/qa/homework_03/aircrafts/Aircraft.java
> +            System.out.println();
Лучше собрать сообщение об ошибке в строку и потом вывести её вместе с сообщением исключения
```java
String errorMessage = "collected message";
throw new IllegalAircraftSpecificationException("Illegal aircraft specification. " + message);
```

2020-12-09 08:40 UTC, khda91 commented on src/main/java/ru/levelup/elena/roshchina/qa/homework_03/aircrafts/Airplane.java
> +import ru.levelup.elena.roshchina.qa.homework_03.aviaexceptions.IllegalAircraftSpecificationException;
Импорт исключения есть, а самого его нету(

2020-12-09 17:40 UTC, elena-roshchina commented on src/main/java/ru/levelup/elena/roshchina/qa/homework_03/aircrafts/AirShip.java
> +import ru.levelup.elena.roshchina.qa.homework_03.aviaexceptions.IllegalAircraftSpecificationException;
Импорт остался от первого варианта кода. Убран.

2020-12-09 17:40 UTC, elena-roshchina commented on src/main/java/ru/levelup/elena/roshchina/qa/homework_03/aircrafts/Airplane.java
> +import ru.levelup.elena.roshchina.qa.homework_03.aviaexceptions.IllegalAircraftSpecificationException;
Импорт остался от первого варианта кода. Убран.

2020-12-09 17:40 UTC, elena-roshchina commented on src/main/java/ru/levelup/elena/roshchina/qa/homework_03/aircrafts/Aircraft.java
> +            System.out.println();
Исправлено.

2020-12-14 15:21 UTC, khda91 approved these changes

2020-12-14 15:22 UTC, khda91 commented
Работа принята

2020-12-21 17:09 UTC, merged